version: '3.7'
services:

  vaenotebook:
    container_name: VAENotebook
    build:
      context: .
      dockerfile: ./src/notebook/Dockerfile
    volumes:
      - ./src/notebook/:/workspace
      - ./assets/data/:/workspace/data
    ports:
      - "8888:8888"
      - "6006:6006"
    user: ${CURRENT_UID}
