version: '3.1'
services:

  vaenotebook:
    container_name: VAENotebook
    build:
      context: .
      dockerfile: ./src/notebook/Dockerfile
    volumes:
      - ./src/notebook/:/home/me
    ports:
      - "8888:8888"
    user: ${CURRENT_UID}
